refactor: migrate numeral to numbro
livepeer/explorer pull request #237
Opened 2023-12-03 14:24 UTC by rickstaa

This pull request deprecates the use of the unmaintained [numeral-js](https://github.com/adamwdraper/Numeral-js) library and replaces it with the [numbro](https://github.com/BenjaminVanRyseghem/numbro). This was done to fix #236 and ensure the explorer is future-proof.

2023-12-03 15:13 UTC, rickstaa commented on components/OrchestratingView/index.tsx
> +            .format({mantissa: 0, output: "percent"})}
This needed to be done since the https://numbrojs.com/ library, by default, shows more significant digits when the "0%" legacy format is used (see https://numbrojs.com/old-format.html).

2023-12-03 15:14 UTC, rickstaa commented on components/OrchestratorList/index.tsx
> +                .format({mantissa:0, output: "precent"})}`,
Here aswell.

2023-12-03 15:14 UTC, rickstaa commented on components/OrchestratorList/index.tsx
> +              {numbro(row.values.totalStake).format({mantissa:0, thousandSeparated: true})} LPT
This was done since the https://numbrojs.com library, by default, shows more significant digits when the `0,0` legacy syntax is used.

2023-12-12 17:23 UTC, 0xcadams requested changes
The build is failing - this may fix it

2023-12-12 17:23 UTC, 0xcadams commented on components/OrchestratorList/index.tsx
> +                .format({mantissa:0, output: "precent"})}`,
```suggestion
                .format({mantissa:0, output: "percent"})}`,
```

2023-12-12 17:23 UTC, 0xcadams commented
Thanks for this! Some changes we can hopefully make here

2023-12-12 18:05 UTC, 0xcadams approved these changes

2023-12-12 18:05 UTC, merged

2023-12-12 18:15 UTC, 0xcadams commented
Hey @rickstaa it looks like this broke the explorer, I had to revert
<img width="1400" alt="Screenshot 2023-12-12 at 11 15 13 AM" src="https://github.com/livepeer/explorer/assets/32714304/87435b00-70d2-4dce-bb2e-54a4957e0d9b">

2023-12-12 18:43 UTC, rickstaa commented
Hi @0xcadams,

No problem at all. As mentioned in my comment on [this pull request](https://github.com/livepeer/explorer/pull/237#issuecomment-1837501185), I apologize for not thoroughly testing all parts of the explorer before submitting it. In hindsight, I should have kept it as a draft. I understand the inconvenience it caused 😅. 

I'd happily create a new pull request to ensure all changes are thoroughly tested. However, I could use some guidance on the best testing practices for all my changes. Specifically, there are two areas of the explorer that I couldn't test:

1. **Overview Widget:** as you've noticed, this widget is currently broken in your screenshot. I couldn't configure the .env file with the correct API key to make the overview widget function properly.

2. **Testing Wallet Display:** The widgets appear when a wallet contains LPT and stakes or unstakes at an orchestrator, and this part of the code needs verification. Unfortunately, the absence of a CONTRIBUTING.md file in this repository has left me uncertain about the best approach for testing these changes. I attempted to find a Goerli LPT test faucet but could not locate one 🤔.

Your guidance on how to effectively test these changes would be greatly appreciated.